### PR TITLE
Fixes #10, Fixes #6, Fixes tests

### LINKED ISSUE #6: add the new functions to the module's dictionary explicitly, so they show up in 'dir' calls.

### LINKED ISSUE #10: sys.modules is called on import
classic error - the modules dict is defined at import time as a default, so if dado happens to be imported before the targeted test module, that module won't show up and dado will freak out when it's called and tries to update the calling module.

### PR DESCRIPTION
**Pull request by toejough**
**Problem:**
The main problem was that the tests weren't passing when run, due to
some import semantics, depending on how you called the tests.

Other problems:
* import-time sys.modules use is a bad practice
* functions were getting set in the __dict__ rather than on the module,
which was sometimes leading to problems with dir not showing the
functions.

**Analysis:**
Issues #10 and #6 didn't seem to really be causing problems on inspection.
They were updated/addressed anyway because the updates follow best practices.

Updating the tests was the bigger piece - they now run reliably and
actually directly test what the module is supposed to do, instead of
mucking about with the mock module.

**Resolution:**
Update the tests to be more direct and functional than abstract and
unit-test-y.

Use a robust import mechanism for the testing.

Use the sys.modules dict *in* the function rather than at import time.

Use setattr on the target module rather than accessing its __dict__.

**Testing:**
Ran the tests.

**Documentation:**
None.

**Impact:**
Patch - small fixups, mostly to the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/notion/dado/11)

### CODE REVIEW

**Review by danjchoi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/notion/dado/11)* status: all files reviewed, 1 unresolved discussion (waiting on @toejough)

___
*[dado.py, line 81 at r1](https://reviewable.io/reviews/notion/dado/11#-LP2-ClI52w2RE0ITE8U:-LP2-ClJ1I8Zvw_wUsI9:bols8ky) ([raw file](https://github.com/notion/dado/blob/a2f6a5e7267c094fbc8032ad3ff617b8b8f5c660/dado.py#L81)):*
> ```Python
>         setattr(get_module(), new_name, new_test)
>         new_funcs.append(new_test)
>     # return None so that the original function will be overwritten
> ```

Update comment?

**Review by toejough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/notion/dado/11)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @danjchoi and @toejough)

___
*[dado.py, line 81 at r1](https://reviewable.io/reviews/notion/dado/11#-LP2-ClI52w2RE0ITE8U:-LP2aF3zE58LQ3Kr-8bI:b-j8a2hl) ([raw file](https://github.com/notion/dado/blob/a2f6a5e7267c094fbc8032ad3ff617b8b8f5c660/dado.py#L81)):*
<details><summary><i>Previously, danjchoi (Daniel Choi) wrote…</i></summary><blockquote>

Update comment?
</blockquote></details>

nah.  reverted and updated the testing.  this change was prepping for allowing us to stack dado decorators.

**Review by toejough — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/notion/dado/11)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @danjchoi and @toejough)

___
*[dado.py, line 81 at r1](https://reviewable.io/reviews/notion/dado/11#-LP2-ClI52w2RE0ITE8U:-LP2aQSQDIKvrGjZRJoF:bum3dxj) ([raw file](https://github.com/notion/dado/blob/a2f6a5e7267c094fbc8032ad3ff617b8b8f5c660/dado.py#L81)):*
<details><summary><i>Previously, toejough (toejough) wrote…</i></summary><blockquote>

nah.  reverted and updated the testing.  this change was prepping for allowing us to stack dado decorators.
</blockquote></details>

(it also wasn't documented in the commit)

**Review by danjchoi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/notion/dado/11)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[dado.py, line 81 at r1](https://reviewable.io/reviews/notion/dado/11#-LP2-ClI52w2RE0ITE8U:-LP2d2Db6Okk1oy1QOtJ:bjmvxn0) ([raw file](https://github.com/notion/dado/blob/a2f6a5e7267c094fbc8032ad3ff617b8b8f5c660/dado.py#L81)):*
<details><summary><i>Previously, toejough (toejough) wrote…</i></summary><blockquote>

(it also wasn't documented in the commit)
</blockquote></details>

Oh haha. That would definitely be neat.

**Review by danjchoi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/notion/dado/11)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
